### ISSUE TITLE
methods clarification

### ISSUE THREAD

**Issue by JiaheXu** [dexsuite/dex-retargeting#1]
Hi @yzqin 

Exciting work! Can you please clarify which methods are used for hand pose estimation and retargeting? I think they are from `https://github.com/yzqin/dex-hand-teleop/tree/main`, just to double-check.

**Comment by yzqin** [comment]
Hi @JiaheXu,

The hand pose estimation part is very similar as the [repo you mentioned](https://github.com/yzqin/dex-hand-teleop/tree/main). However, the retargeting method is developed based on previous repo and make it much better than previous one. It achieve faster speed and better optimization compared with retargeting method used in our previous work.
