### ISSUE TITLE
error during visualizing robot hand-object Interaction

### ISSUE THREAD

**Issue by haoyangzhanglab** [dexsuite/dex-retargeting#12]
I have followed the instructions and successfully visualized human hand interaction. However, when using this command to visualize robot hand interaction, the following error occurred. Is there any way to fix this problem? Thank you!
![image](https://github.com/dexsuite/dex-retargeting/assets/131220673/464b342d-171c-40f7-bebb-ed5422752175)
**command:**
`python3 visualize_hand_object.py --dexycb-dir=./dexycb --robots allegro shadow svh`
**error:**
![image](https://github.com/dexsuite/dex-retargeting/assets/131220673/43c2bac2-c709-40c0-ade9-a979e16f00f7)

**Comment by yzqin** [comment]
Hi @haoyangzhanglab 

Thanks for your information. There are some compatibility issues for the previous version, **which is fixed now**. I have updated both the code and the README for this example. Please follow the updated README with the latest version of the dex_retargeting package (0.3.1).
