### ISSUE TITLE
hand detection retarget not accurate

### ISSUE THREAD

**Issue by xbkaishui** [dexsuite/dex-retargeting#16]
hello 

I have tested the hand detection retarget using allegro hand.  the test code is [ pr ](https://github.com/dexsuite/dex-retargeting/pull/15)

I found some position is not accurate, below are some test snapshots

 
![image](https://github.com/dexsuite/dex-retargeting/assets/1477791/626d27d6-8e6b-4ec0-a393-760b53e591d2)
![image](https://github.com/dexsuite/dex-retargeting/assets/1477791/c4f62c10-fdfe-4b55-8549-9f37712e8dba)

### tested env:

- camera:  built-in camera on the computer is used.
- pc board name rog7
- system:  windows 11

**Comment by yzqin** [comment]
Hi @xbkaishui 

This is a common issue of detection error. Luckily, the detection error can be mitigated by using a different retargeting algorithm.

I believe you are using the `RetargetingType.vector` as retargeting type, can you try with `RetargetingType.dexpilot`, I think it will solve the problem you mentioned above. 

By the way, thanks for the PR. I will review it and add it to the main repo with some small modifications.

**Comment by yzqin** [comment]
Hi @xbkaishui 

I have merged your PR and updated the README for vector retargeting. I have also uploaded an example video captured on my own using the allegro hand with `dexpilot` retargeting config. Maybe you can take a look:

https://github.com/dexsuite/dex-retargeting/tree/main/example/vector_retargeting

**Comment by xbkaishui** [comment]
> Hi @xbkaishui
> 
> This is a common issue of detection error. Luckily, the detection error can be mitigated by using a different retargeting algorithm.
> 
> I believe you are using the `RetargetingType.vector` as retargeting type, can you try with `RetargetingType.dexpilot`, I think it will solve the problem you mentioned above.
> 
> By the way, thanks for the PR. I will review it and add it to the main repo with some small modifications.



> Hi @xbkaishui
> 
> This is a common issue of detection error. Luckily, the detection error can be mitigated by using a different retargeting algorithm.
> 
> I believe you are using the `RetargetingType.vector` as retargeting type, can you try with `RetargetingType.dexpilot`, I think it will solve the problem you mentioned above.
> 
> By the way, thanks for the PR. I will review it and add it to the main repo with some small modifications.

hello， sorry to bother you again. i use dexpilot.  after some debug, I found that it is the mediapipe detection algo not so accurate. thanks for your response

**Comment by xbkaishui** [comment]
> Hi @xbkaishui
> 
> I have merged your PR and updated the README for vector retargeting. I have also uploaded an example video captured on my own using the allegro hand with `dexpilot` retargeting config. Maybe you can take a look:
> 
> https://github.com/dexsuite/dex-retargeting/tree/main/example/vector_retargeting



> Hi @xbkaishui
> 
> I have merged your PR and updated the README for vector retargeting. I have also uploaded an example video captured on my own using the allegro hand with `dexpilot` retargeting config. Maybe you can take a look:
> 
> https://github.com/dexsuite/dex-retargeting/tree/main/example/vector_retargeting

thanks

**Comment by BIT-wh** [comment]
> hello
> 
> I have tested the hand detection retarget using allegro hand. the test code is [ pr ](https://github.com/dexsuite/dex-retargeting/pull/15)
> 
> I found some position is not accurate, below are some test snapshots
> 
> ![image](https://private-user-images.githubusercontent.com/1477791/334285353-626d27d6-8e6b-4ec0-a393-760b53e591d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTgyODQsIm5iZiI6MTcxODA5Nzk4NCwicGF0aCI6Ii8xNDc3NzkxLzMzNDI4NTM1My02MjZkMjdkNi04ZTZiLTRlYzAtYTM5My03NjBiNTNlNTkxZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDkyNjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWUzNTdhYzdiYjdlMTVhNDZkYmNmMzAwNWI2NWViMGZhMzk2YzEzMTE0ZDcwZDlkNjUzOTkxZmIzMTA3NDdlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Pp4jFi0UA1RaiD2By-3SpZgv4zP_Zu80Nqki5xYGEcU) ![image](https://private-user-images.githubusercontent.com/1477791/334285389-c4f62c10-fdfe-4b55-8549-9f37712e8dba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTgyODQsIm5iZiI6MTcxODA5Nzk4NCwicGF0aCI6Ii8xNDc3NzkxLzMzNDI4NTM4OS1jNGY2MmMxMC1mZGZlLTRiNTUtODU0OS05ZjM3NzEyZThkYmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDkyNjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTVlMzYwMDA2MmFlOTk3NWQ3NWU2Zjc4MmU2ZGRkNTNlNmI2OGFkOWI1NGRlODgyYzRjNTkyYzBlYjQ3ZmU4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hstkig9LDAs2USPS3F7QiMYJBsv2TogppUIVpAUfvvg)
> 
> ### tested env:
> * camera:  built-in camera on the computer is used.
> * pc board name rog7
> * system:  windows 11

Hi, sorry to bother you. I have a problem in install dex-retargeting in Windows11. When I install it, it makes a mistake in install pin. Then I use `conda install pinocchio -c conda-forge` to install. It works, but when I use `pip install dex_retargeting`, It still downloads` /pin-2.7.0.tar.gz` and then reports an error, as before. Bro, how did you download it in win11?  Looking forward to your reply, thank you !

**Comment by xbkaishui** [comment]
> > hello
> > I have tested the hand detection retarget using allegro hand. the test code is [ pr ](https://github.com/dexsuite/dex-retargeting/pull/15)
> > I found some position is not accurate, below are some test snapshots
> > ![image](https://private-user-images.githubusercontent.com/1477791/334285353-626d27d6-8e6b-4ec0-a393-760b53e591d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTgyODQsIm5iZiI6MTcxODA5Nzk4NCwicGF0aCI6Ii8xNDc3NzkxLzMzNDI4NTM1My02MjZkMjdkNi04ZTZiLTRlYzAtYTM5My03NjBiNTNlNTkxZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDkyNjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWUzNTdhYzdiYjdlMTVhNDZkYmNmMzAwNWI2NWViMGZhMzk2YzEzMTE0ZDcwZDlkNjUzOTkxZmIzMTA3NDdlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Pp4jFi0UA1RaiD2By-3SpZgv4zP_Zu80Nqki5xYGEcU) ![image](https://private-user-images.githubusercontent.com/1477791/334285389-c4f62c10-fdfe-4b55-8549-9f37712e8dba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTgyODQsIm5iZiI6MTcxODA5Nzk4NCwicGF0aCI6Ii8xNDc3NzkxLzMzNDI4NTM4OS1jNGY2MmMxMC1mZGZlLTRiNTUtODU0OS05ZjM3NzEyZThkYmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDkyNjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTVlMzYwMDA2MmFlOTk3NWQ3NWU2Zjc4MmU2ZGRkNTNlNmI2OGFkOWI1NGRlODgyYzRjNTkyYzBlYjQ3ZmU4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hstkig9LDAs2USPS3F7QiMYJBsv2TogppUIVpAUfvvg)
> > ### tested env:
> > 
> > * camera:  built-in camera on the computer is used.
> > * pc board name rog7
> > * system:  windows 11
> 
> Hi, sorry to bother you. I have a problem in install dex-retargeting in Windows11. When I install it, it makes a mistake in install pin. Then I use `conda install pinocchio -c conda-forge` to install. It works, but when I use `pip install dex_retargeting`, It still downloads` /pin-2.7.0.tar.gz` and then reports an error, as before. Bro, how did you download it in win11? Looking forward to your reply, thank you !

use conda install 

conda install pinocchio -c conda-forge
