### ISSUE TITLE
Issue running "pip3 install -e ."

### ISSUE THREAD

**Issue by Alif-11** [dexsuite/dex-retargeting#18]
Hello! I am trying to use this repo for a project, but I am running into build issues. 
I have attached a file with the terminal error output below. I am on a Mac running Sonoma 14.1.2, using a pyenv virtualenv environment running Python 3.8.19. Is there a specific Python version I should be running? It's saying there is an issue with nlopt.

[error.txt](https://github.com/user-attachments/files/15571821/error.txt)

**Comment by yzqin** [comment]
It seems that you get an error when running `pip install nlopt`.

Can you try a standalone `pip install nlopt` and see what will happen. I am not sure whether nlopt support the latest Mac version but you can check their compatbility here: https://pypi.org/project/nlopt/2.7.1/#files

If problem still exisiting, maybe you can rasie an issue in the nlopt Github repo: https://github.com/stevengj/nlopt
