### ISSUE TITLE
Expand the retargeting algorithm to 2 arm-hand system

### ISSUE THREAD

**Issue by Terrywang2001** [dexsuite/dex-retargeting#21]
Hi, thank you for your astonishing work! Right now I have a self-designed humanoid robot with two arms and I want apply your retargeting algorithm to the whole upper body of my robot. So I want to teleop my robot, just the two arms on its upper body, in a sim environment just using the dex-retargeting algorithm. But I am not sure how to make the retargeting algorithm work on the humanoid robot arms such that it could mimic the human operator's action.

**Comment by yzqin** [comment]
Maybe you can check our open-source repo on bimanual upper teleoperation: https://github.com/Dingry/BunnyVisionPro
