### ISSUE TITLE
teleop on physic simulator to collect data

### ISSUE THREAD

**Issue by levi3001** [dexsuite/dex-retargeting#22]
Thank you for your amazing work. I am recently use your code to collect some demonstration data for my project. I can see from your prior work [](https://github.com/yzqin/dex-hand-teleop/tree/main), that you can control the hand on an predefined environment and I also expect that you can do this with this project. Do you have any plan to provide another example file for this task or can you give me a brief instruction of how to do this task?
Thank you

**Comment by yzqin** [comment]
For integrating the retargeting code into the simulator, you can refer to [my other repo](https://github.com/yzqin/dex-hand-teleop). This repo is fully targeted at hand retargeting implementation.
