### ISSUE TITLE
The vector retargeting readme is incomplete

### ISSUE THREAD

**Issue by JackMa-coder** [dexsuite/dex-retargeting#3]
Thank you for your excellent and useful work. 
I have noticed that  [vector retargeting readme](https://github.com/dexsuite/dex-retargeting/blob/4c55d2111379e8236f415cc8643dd0ec67c6d028/example/vector_retargeting/README.md) is incomplete and I attempted to use vector retargeting by following the method of position retargeting, but observed a large position error in the dexterous hand.
I look forward to your plan to supplement it.

**Comment by yzqin** [comment]
I was wondering that which part of the vector retargeting readme is incomplete. I think we provide a self-contained example for detecting and retargeting from video.
