### ISSUE TITLE
some mistake when I install dex-retargeting

### ISSUE THREAD

**Issue by git-xuefu** [dexsuite/dex-retargeting#32]
Hi，it's a awesome work.But,when I install the dex-retargeting, there are some mistakes,can you tell me how to solve it,Thanks!

        D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libiconv.a when searching for -liconv
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -liconv
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libmingwthrd.a when searching for -lmingwthrd
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib\libmingwthrd.a when searching for -lmingwthrd
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libmingwthrd.a when searching for -lmingwthrd
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwthrd
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libmingw32.a when searching for -lmingw32
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib\libmingw32.a when searching for -lmingw32
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libmingw32.a when searching for -lmingw32
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingw32
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libgcc_s.a when searching for -lgcc_s
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib\libgcc_s.a when searching for -lgcc_s
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libgcc_s.a when searching for -lgcc_s
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc_s
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgcc.a when searching for -lgcc
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0\libgcc.a when searching for -lgcc
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgcc.a when searching for -lgcc
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libmoldname.a when searching for -lmoldname
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib\libmoldname.a when searching for -lmoldname
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libmoldname.a when searching for -lmoldname
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmoldname
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libmingwex.a when searching for -lmingwex
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib\libmingwex.a when searching for -lmingwex
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libmingwex.a when searching for -lmingwex
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwex
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libmsvcrt.a when searching for -lmsvcrt
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib\libmsvcrt.a when searching for -lmsvcrt
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/lib/libmsvcrt.a when searching for -lmsvcrt
          D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt
        collect2.exe : error : ld returned 1 exit status [C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\Boost.vcxproj]

              "g++"   -Wl,--out-implib,"bin.v2\libs\contract\build\gcc-8\debug\address-model-32\threadapi-win32\threading-multi\visibility-hidden\libboost_contract-mgw8-mt-d-x32-1_83.dll.a" -o "bin.v2\libs\contract\build\gcc-8\debug\address-model-32\threadapi-win32\threading-multi\visibility-hidden\libboost_contract-mgw8-mt-d-x32-1_83.dll"  -shared -Wl,--start-group "bin.v2/libs/contract/build/gcc-8/debug/address-model-32/threadapi-win32/threading-multi/visibility-hidden/contract.o"  -Wl,-Bstatic  -Wl,-Bdynamic  -Wl,--end-group -m32 -mthreads -g -fvisibility=hidden -fvisibility-inlines-hidden -march=i686

          ...failed gcc.link.dll bin.v2\libs\contract\build\gcc-8\debug\address-model-32\threadapi-win32\threading-multi\visibility-hidden\libboost_contract-mgw8-mt-d-x32-1_83.dll bin.v2\libs\contract\build\gcc-8\debug\address-model-32\threadapi-win32\threading-multi\visibility-hidden\libboost_contract-mgw8-mt-d-x32-1_83.dll.a...
          ...skipped <pC:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\Boost-prefix\src\Boost\stage\lib>libboost_contract-mgw8-mt-d-x32-1_83.dll.a for lack of <pbin.v2\libs\contract\build\gcc-8\debug\address-model-32\threadapi-win32\threading-multi\visibility-hidden>libboost_contract-mgw8-mt-d-x32-1_83.dll.a...
          ...skipped <pbin.v2\libs\contract\build\gcc-8\debug\address-model-32\threadapi-win32\threading-multi\visibility-hidden>libboost_contract-variant-mgw8-mt-d-x32-1_83-shared.cmake for lack of <pbin.v2\libs\contract\build\gcc-8\debug\address-model-32\threadapi-win32\threading-multi\visibility-hidden>libboost_contract-mgw8-mt-d-x32-1_83.dll.a...
          ...skipped <pC:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\Boost-prefix\src\Boost\stage\lib\cmake\boost_contract-1.83.0>libboost_contract-variant-mgw8-mt-d-x32-1_83-shared.cmake for lack of <pbin.v2\libs\contract\build\gcc-8\debug\address-model-32\threadapi-win32\threading-multi\visibility-hidden>libboost_contract-variant-mgw8-mt-d-x32-1_83-shared.cmake...
          ...skipped <pC:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\Boost-prefix\src\Boost\stage\lib>libboost_contract-mgw8-mt-d-x32-1_83.dll for lack of <pbin.v2\libs\contract\build\gcc-8\debug\address-model-32\threadapi-win32\threading-multi\visibility-hidden>libboost_contract-mgw8-mt-d-x32-1_83.dll...
          gcc.compile.c++ bin.v2\libs\test\build\gcc-8\release\link-static\threadapi-win32\threading-multi\visibility-hidden\unit_test_parameters.o
          gcc.archive bin.v2\libs\test\build\gcc-8\release\link-static\threadapi-win32\threading-multi\visibility-hidden\libboost_test_exec_monitor-mgw8-mt-x64-1_83.a
          boost-install.generate-cmake-variant- bin.v2\libs\test\build\gcc-8\release\threadapi-win32\threading-multi\visibility-hidden\libboost_test_exec_monitor-variant-mgw8-mt-x64-1_83-shared.cmake
          common.copy C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\Boost-prefix\src\Boost\stage\lib\libboost_test_exec_monitor-mgw8-mt-x64-1_83.a
          bin.v2\libs\test\build\gcc-8\release\link-static\threadapi-win32\threading-multi\visibility-hidden\libboost_test_exec_monitor-mgw8-mt-x64-1_83.a
          已复制         1 个文件。
          common.copy C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\Boost-prefix\src\Boost\stage\lib\cmake\boost_test_exec_monitor-1.83.0\libboost_test_exec_monitor-variant-mgw8-mt-x64-1_83-shared.cmake
          bin.v2\libs\test\build\gcc-8\release\threadapi-win32\threading-multi\visibility-hidden\libboost_test_exec_monitor-variant-mgw8-mt-x64-1_83-shared.cmake
          已复制         1 个文件。
          gcc.compile.c++ bin.v2\libs\test\build\gcc-8\release\threadapi-win32\threading-multi\visibility-hidden\unit_test_parameters.o
          gcc.link.dll bin.v2\libs\test\build\gcc-8\release\threadapi-win32\threading-multi\visibility-hidden\libboost_unit_test_framework-mgw8-mt-x64-1_83.dll
          boost-install.generate-cmake-variant- bin.v2\libs\test\build\gcc-8\release\threadapi-win32\threading-multi\visibility-hidden\libboost_unit_test_framework-variant-mgw8-mt-x64-1_83-shared.cmake
          common.copy C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\Boost-prefix\src\Boost\stage\lib\libboost_unit_test_framework-mgw8-mt-x64-1_83.dll.a
          bin.v2\libs\test\build\gcc-8\release\threadapi-win32\threading-multi\visibility-hidden\libboost_unit_test_framework-mgw8-mt-x64-1_83.dll.a
          已复制         1 个文件。
          common.copy C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\Boost-prefix\src\Boost\stage\lib\libboost_unit_test_framework-mgw8-mt-x64-1_83.dll
          bin.v2\libs\test\build\gcc-8\release\threadapi-win32\threading-multi\visibility-hidden\libboost_unit_test_framework-mgw8-mt-x64-1_83.dll
          已复制         1 个文件。
          common.copy C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\Boost-prefix\src\Boost\stage\lib\cmake\boost_unit_test_framework-1.83.0\libboost_unit_test_framework-variant-mgw8-mt-x64-1_83-shared.cmake
          bin.v2\libs\test\build\gcc-8\release\threadapi-win32\threading-multi\visibility-hidden\libboost_unit_test_framework-variant-mgw8-mt-x64-1_83-shared.cmake
          已复制         1 个文件。
          ...failed updating 230 targets...
          ...skipped 388 targets...
          ...updated 2653 targets...
        D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: “C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\CMakeFiles\ecb668bdd6e11d986b6462262c54eb0e\Boost-mkdir.rule;C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\CMakeFiles\ecb668bdd6e11d986b6462262c54eb0e\Boost-download.rule;C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\CMakeFiles\ecb668bdd6e11d986b6462262c54eb0e\Boost-update.rule;C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\CMakeFiles\ecb668bdd6e11d986b6462262c54eb0e\Boost-patch.rule;C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\CMakeFiles\ecb668bdd6e11d986b6462262c54eb0e\Boost-configure.rule;C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\CMakeFiles\ecb668bdd6e11d986b6462262c54eb0e\Boost-build.rule;C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\CMakeFiles\ecb668bdd6e11d986b6462262c54eb0e\Boost-install.rule;C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\CMakeFiles\9aa490dbb77bafc338be7dfd579e1caf\Boost-complete.rule;C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\CMakeFiles\e52843a58e34fe020e7adf5730fa0819\Boost.rule;C:\Users\26380\AppData\Local\Temp\pip-install-hnca9yha\cmeel-boost_eb6c845c09154627a2125bee967c4b60\CMakeLists.txt”的自定义生成已退出，代码为 1。 [C:\Users\26380\AppData\Local\Temp\cmeel-t462nbw5\bld\Boost.vcxproj]
        Traceback (most recent call last):
          File "D:\anaconda\envs\Keypoint\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "D:\anaconda\envs\Keypoint\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "D:\anaconda\envs\Keypoint\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
            whl_basename = backend.build_wheel(metadata_directory, config_settings)
          File "C:\Users\26380\AppData\Local\Temp\pip-build-env-h285gmkd\overlay\Lib\site-packages\cmeel\build.py", line 26, in build_wheel
            return build_impl(wheel_directory, editable=False)
          File "C:\Users\26380\AppData\Local\Temp\pip-build-env-h285gmkd\overlay\Lib\site-packages\cmeel\impl.py", line 105, in build_impl
            check_call(build_cmd)
          File "D:\anaconda\envs\Keypoint\lib\subprocess.py", line 373, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['cmake', '--build', 'C:\\Users\\26380\\AppData\\Local\\Temp\\cmeel-t462nbw5\\bld', '-j4']' returned non-zero exit status 1.
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by yzqin** [comment]
From the debug information above, it seems that it is an issue related to your environment, where some basic library is missing, e.g. `mingw32`, `moldname`. This issue will also influence other libraries, e.g. opencv-python.

If you find it tricky to config the environment on windows, maybe you can consider use a Linux virtual machine.
