### ISSUE TITLE
How can I retargeting with my hand keypoints as input?

### ISSUE THREAD

**Issue by git-xuefu** [dexsuite/dex-retargeting#36]
Thanks for your work! I want to use my network output hand keypoints as input for retargeting.How can I use your code to do this?

**Comment by yzqin** [comment]
Definitely. This repo only focuses on hand retargeting, feel free to use your trained perception network. 

For example, you can replace the https://github.com/dexsuite/dex-retargeting/blob/main/example/vector_retargeting/single_hand_detector.py with some detector based on your own network.
