### ISSUE TITLE
Recommended Python Version

### ISSUE THREAD

**Issue by MARMOTatZJU** [dexsuite/dex-retargeting#38]
Hi, thanks for open-sourcing this project!

I would like to know the Python version recommended for running the retargeting code, which I was not able to found in the documentation. Thanks in advance!

**Comment by yzqin** [comment]
Hi @MARMOTatZJU 

I am using Python 3.10 for the codebase. I believe that 3.11 and 3.12 can also work.

**Comment by MARMOTatZJU** [comment]
> Hi @MARMOTatZJU 
> 
> I am using Python 3.10 for the codebase. I believe that 3.11 and 3.12 can also work.
> 
> 

Cool, many thanks for your answer!

- 發自我的手機
