### ISSUE TITLE
module 'sapien' has no attribute 'render'

### ISSUE THREAD

**Issue by nlnlz** [dexsuite/dex-retargeting#44]
I have  this question ( sapien version == 2.2), how to solve?
module 'sapien' has no attribute 'render'

**Comment by yzqin** [comment]
The core module of dex_retargeting does not relies on sapien. 
If you would like to run the examples, which use sapien for visualization, you can install it with 

```bash
cd THIS_REPO
pip install ".[example]"
```

Alternatively, you can install it with `pip install sapien==3.0.0b2`. The required sapien version can be find in the [setup.py](https://github.com/dexsuite/dex-retargeting/blob/8274cd4df69c5d81c1935b910e0114515ebd9315/setup.py#L63)
