### ISSUE TITLE
How to make yml ?

### ISSUE THREAD

**Issue by 1024AILab** [dexsuite/dex-retargeting#49]
Thank you for your wonderful work! I am curious about how to make yml for my robot(xarm7 + allegro hand).

![image](https://github.com/user-attachments/assets/2d792095-651c-45d3-8ace-d2ac20e5a743)
![image](https://github.com/user-attachments/assets/1dc386c4-dfb7-4a22-8ea6-13efdf785e3d)
[xarm7_allegro_vertical.zip](https://github.com/user-attachments/files/18045550/xarm7_allegro_vertical.zip)

**Comment by yzqin** [comment]
The retargeting part is more for the dexterous hand. The config of allegro hand is already provided in the default config. You can directly use the allegro hand config for your robot.
